apiVersion: v1
kind: Pod
metadata:
  name: static-web-large
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
